import { GLTF } from 'three-stdlib'

export interface RoomState {

}

export type GLTFResult = GLTF & {
  nodes: {
    shiba: THREE.Mesh
    Windows_Sill: THREE.Mesh
    windowframe: THREE.Mesh
    curtain_r: THREE.Mesh
    curtain_top: THREE.Mesh
    curtain_l: THREE.Mesh
    pillow: THREE.Mesh
    mattress: THREE.Mesh
    Cube107: THREE.Mesh
    Cube107_1: THREE.Mesh
    laptop016: THREE.Mesh
    Cube061: THREE.Mesh
    Cube061_1: THREE.Mesh
    Handle001: THREE.Mesh
    Handle: THREE.Mesh
    desk_5: THREE.Mesh
    Cylinder008: THREE.Mesh
    Cylinder008_1: THREE.Mesh
    Sphere001: THREE.Mesh
    Sphere001_1: THREE.Mesh
    note008: THREE.Mesh
    Cube018: THREE.Mesh
    Cube018_1: THREE.Mesh
    UTMIST: THREE.Mesh
    Cube038: THREE.Mesh
    Cube038_1: THREE.Mesh
    welcome: THREE.Mesh
    welcome_keyboard: THREE.Mesh
    Cube040: THREE.Mesh
    Cube040_1: THREE.Mesh
    welcome_monitor: THREE.Mesh
    Cube041: THREE.Mesh
    Cube041_1: THREE.Mesh
    welcome_window: THREE.Mesh
    desk_6: THREE.Mesh
    Plane007: THREE.Mesh
    Plane007_1: THREE.Mesh
    Plane007_2: THREE.Mesh
    Plane007_3: THREE.Mesh
    Sphere: THREE.Mesh
    Sphere_1: THREE.Mesh
    Sphere_2: THREE.Mesh
    microphone: THREE.Mesh
    note009: THREE.Mesh
    Cylinder014: THREE.Mesh
    Cylinder014_1: THREE.Mesh
    Cylinder014_2: THREE.Mesh
    Cylinder018: THREE.Mesh
    Cylinder018_1: THREE.Mesh
    Cylinder018_2: THREE.Mesh
    Vert004: THREE.Mesh
    Vert004_1: THREE.Mesh
    piano_lid: THREE.Mesh
    ping_pong_ball: THREE.Mesh
    doorway: THREE.Mesh
    door002: THREE.Mesh
    desk009: THREE.Mesh
    desk008: THREE.Mesh
    desk_1: THREE.Mesh
    desk_2: THREE.Mesh
    desk_legs: THREE.Mesh
    Cube012: THREE.Mesh
    Cube012_1: THREE.Mesh
    Cube012_2: THREE.Mesh
    H: THREE.Mesh
    L: THREE.Mesh
    M: THREE.Mesh
    note005: THREE.Mesh
    ramuri: THREE.Mesh
    desk_3: THREE.Mesh
    Cube027: THREE.Mesh
    Cube027_1: THREE.Mesh
    Cylinder009: THREE.Mesh
    Cylinder009_1: THREE.Mesh
    note006: THREE.Mesh
    desk003: THREE.Mesh
    nightstand: THREE.Mesh
    desk_4: THREE.Mesh
    Vert001: THREE.Mesh
    Vert001_1: THREE.Mesh
    Vert001_2: THREE.Mesh
    CSS: THREE.Mesh
    figma: THREE.Mesh
    firebase: THREE.Mesh
    git: THREE.Mesh
    HTML: THREE.Mesh
    JS: THREE.Mesh
    nextjs: THREE.Mesh
    note007: THREE.Mesh
    Redux: THREE.Mesh
    Redux002: THREE.Mesh
    tailwindcss: THREE.Mesh
    TS: THREE.Mesh
    desk: THREE.Mesh
    Cylinder003: THREE.Mesh
    Cylinder003_1: THREE.Mesh
    silver_lamp: THREE.Mesh
    pen: THREE.Mesh
    lampshade: THREE.Mesh
    nightstand_lamp: THREE.Mesh
    wall_l: THREE.Mesh
    wall_r: THREE.Mesh
    floor: THREE.Mesh
    closet_body: THREE.Mesh
    closet_rod: THREE.Mesh
    book002: THREE.Mesh
    Cube011: THREE.Mesh
    Cube011_1: THREE.Mesh
    Cube007: THREE.Mesh
    Cube007_1: THREE.Mesh
    blanket: THREE.Mesh
    bed_head: THREE.Mesh
    bed_frame: THREE.Mesh
    Cube110: THREE.Mesh
    Cube110_1: THREE.Mesh
    Cube110_2: THREE.Mesh
    AC: THREE.Mesh
    Cube009: THREE.Mesh
    Cube009_1: THREE.Mesh
    Cube009_2: THREE.Mesh
    Sphere008: THREE.Mesh
    Sphere008_1: THREE.Mesh
    Sphere008_2: THREE.Mesh
    antenna001: THREE.Mesh
    note011: THREE.Mesh
    vocalverse: THREE.Mesh
    Cylinder006: THREE.Mesh
    Cylinder006_1: THREE.Mesh
    Cylinder006_2: THREE.Mesh
    lumigui: THREE.Mesh
    NEAR: THREE.Mesh
    note010: THREE.Mesh
    qhacks: THREE.Mesh
    uottahack: THREE.Mesh
    michael_20: THREE.Mesh
    drawer_case: THREE.Mesh
    Cube080: THREE.Mesh
    Cube080_1: THREE.Mesh
    Cube080_2: THREE.Mesh
    Cube081: THREE.Mesh
    Cube081_1: THREE.Mesh
    Cube081_2: THREE.Mesh
    Cube082: THREE.Mesh
    Cube082_1: THREE.Mesh
    Cube082_2: THREE.Mesh
    devpost: THREE.Mesh
    Discord: THREE.Mesh
    insta: THREE.Mesh
    linkedin: THREE.Mesh
    github: THREE.Mesh
    mlh_shirt: THREE.Mesh
    hangar002: THREE.Mesh
    arts_shirt: THREE.Mesh
    hangar001: THREE.Mesh
    dress_shirt: THREE.Mesh
    hangar: THREE.Mesh
    pants: THREE.Mesh
    hangar004: THREE.Mesh
    shorts: THREE.Mesh
    hangar003: THREE.Mesh
    Cube: THREE.Mesh
    Cube_1: THREE.Mesh
    Cube039: THREE.Mesh
    Cube039_1: THREE.Mesh
    trash_can: THREE.Mesh
    trash_bag: THREE.Mesh
    notebook_back: THREE.Mesh
    Cube078: THREE.Mesh
    Cube078_1: THREE.Mesh
    Cube078_2: THREE.Mesh
    notebook_binding: THREE.Mesh
    Cube044: THREE.Mesh
    Cube044_1: THREE.Mesh
    chair_legs: THREE.Mesh
    chair_back: THREE.Mesh
    seat: THREE.Mesh
    Cube005: THREE.Mesh
    Cube005_1: THREE.Mesh
    Cube005_2: THREE.Mesh
    Cube008: THREE.Mesh
    Cube008_1: THREE.Mesh
    Cube008_2: THREE.Mesh
    Cube017: THREE.Mesh
    Cube017_1: THREE.Mesh
    Cube017_2: THREE.Mesh
    Plane001: THREE.Mesh
    Plane001_1: THREE.Mesh
    Plane001_2: THREE.Mesh
    Plane001_3: THREE.Mesh
    Plane001_4: THREE.Mesh
    clock001: THREE.Mesh
    clock002: THREE.Mesh
  }
  materials: {
    shiba: THREE.MeshStandardMaterial
    Sill_material: THREE.MeshStandardMaterial
    ['gray.004']: THREE.MeshStandardMaterial
    hotel_sheet: THREE.MeshStandardMaterial
    gray: THREE.MeshStandardMaterial
    ['gray.001']: THREE.MeshStandardMaterial
    laptop_screen: THREE.MeshStandardMaterial
    laptop: THREE.MeshStandardMaterial
    ['laptop.001']: THREE.MeshStandardMaterial
    Plastic_Handle_material: THREE.MeshStandardMaterial
    yellow: THREE.MeshStandardMaterial
    ['orange.005']: THREE.MeshStandardMaterial
    notes: THREE.MeshStandardMaterial
    ['RoRe_tex_metallic.001']: THREE.MeshStandardMaterial
    RoRe: THREE.MeshStandardMaterial
    UTMIST: THREE.MeshStandardMaterial
    ['gray.005']: THREE.MeshStandardMaterial
    sans_eye: THREE.MeshStandardMaterial
    turquoise: THREE.MeshStandardMaterial
    ['gray.002']: THREE.MeshStandardMaterial
    ['red.002']: THREE.MeshStandardMaterial
    ['red.003']: THREE.MeshStandardMaterial
    ['blue.001']: THREE.MeshStandardMaterial
    orange: THREE.MeshStandardMaterial
    piano: THREE.MeshStandardMaterial
    ['orange.002']: THREE.MeshStandardMaterial
    mattress: THREE.MeshStandardMaterial
    desk_screen: THREE.MeshStandardMaterial
    ['yellow.002']: THREE.MeshStandardMaterial
    ramuri: THREE.MeshStandardMaterial
    diploma: THREE.MeshStandardMaterial
    IB: THREE.MeshStandardMaterial
    Bayview: THREE.MeshStandardMaterial
    ['blue.002']: THREE.MeshStandardMaterial
    skills: THREE.MeshStandardMaterial
    react: THREE.MeshStandardMaterial
    ['gray.003']: THREE.MeshStandardMaterial
    books: THREE.MeshStandardMaterial
    ['turquoise.003']: THREE.MeshStandardMaterial
    ['red.005']: THREE.MeshStandardMaterial
    wood_dark: THREE.MeshStandardMaterial
    ['orange.003']: THREE.MeshStandardMaterial
    AC: THREE.MeshStandardMaterial
    ['covermegpt.002']: THREE.MeshStandardMaterial
    ['covermegpt.003']: THREE.MeshStandardMaterial
    ['gray.007']: THREE.MeshStandardMaterial
    hackathons: THREE.MeshStandardMaterial
    lumigui: THREE.MeshStandardMaterial
    ['yellow.003']: THREE.MeshStandardMaterial
    discord: THREE.MeshStandardMaterial
    clothes: THREE.MeshStandardMaterial
    figma: THREE.MeshStandardMaterial
    figma_2: THREE.MeshStandardMaterial
    /* gray: THREE.MeshStandardMaterial */
    ['gray.003']: THREE.MeshStandardMaterial
    ['gray.004']: THREE.MeshStandardMaterial
    gold: THREE.MeshStandardMaterial
  }
}