/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 -t skillsrotated.glb 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import Logo from '@/components/Logo'

type GLTFResult = GLTF & {
  nodes: {
    TS001: THREE.Mesh
    tailwindcss001: THREE.Mesh
    Redux001: THREE.Mesh
    Redux003: THREE.Mesh
    python001: THREE.Mesh
    nextjs001: THREE.Mesh
    JS001: THREE.Mesh
    HTML001: THREE.Mesh
    git001: THREE.Mesh
    firebase001: THREE.Mesh
    figma001: THREE.Mesh
    Vert005: THREE.Mesh
    Vert005_1: THREE.Mesh
    Vert005_2: THREE.Mesh
  }
  materials: {
    skills: THREE.MeshStandardMaterial
    react: THREE.MeshStandardMaterial
    ['orange.001']: THREE.MeshStandardMaterial
    ['blue.001']: THREE.MeshStandardMaterial
    ['gray.002']: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function SkillsRotated({ setIndex, ...props }: any) {
  const { nodes, materials } = useGLTF('/skillsrotated.glb') as GLTFResult

  return (
    <group {...props} dispose={null} scale={6} rotation={[0, Math.PI / 2, 0]} position={[0, 1, 0]}>
      <Logo onPointerOver={() => setIndex(2)} key={0} geometry={nodes.TS001.geometry} material={materials.skills} position={[0.022, 0.265, 0.132]} />
      <Logo onPointerOver={() => setIndex(0)} key={1} geometry={nodes.tailwindcss001.geometry} material={materials.skills} position={[0.044, 0.275, -0.424]} />
      <Logo onPointerOver={() => setIndex(9)} key={2} geometry={nodes.Redux001.geometry} material={materials.react} position={[0.026, -0.328, -0.136]} />
      <Logo onPointerOver={() => setIndex(10)} key={3} geometry={nodes.Redux003.geometry} material={materials.skills} position={[0.022, -0.328, 0.138]} />
      <Logo onPointerOver={() => setIndex(7)} key={4} geometry={nodes.python001.geometry} material={materials.skills} position={[-0.008, -0.028, 0.439]} />
      <Logo onPointerOver={() => setIndex(8)} key={5} geometry={nodes.nextjs001.geometry} material={materials.skills} position={[0.022, -0.341, -0.429]} />
      <Logo onPointerOver={() => setIndex(6)} key={6} geometry={nodes.JS001.geometry} material={materials.skills} position={[0.022, -0.002, 0.132]} />
      <Logo onPointerOver={() => setIndex(3)} key={7} geometry={nodes.HTML001.geometry} material={materials.skills} position={[0.02, 0.26, 0.41]} />
      <Logo onPointerOver={() => setIndex(4)} key={8} geometry={nodes.git001.geometry} material={materials.skills} position={[0.022, -0.014, -0.424]} />
      <Logo onPointerOver={() => setIndex(5)} key={9} geometry={nodes.firebase001.geometry} material={materials.skills} position={[0.022, -0.014, -0.138]} />
      <Logo onPointerOver={() => setIndex(1)} key={10} geometry={nodes.figma001.geometry} material={materials.skills} position={[0.07, 0.284, -0.134]} />
      <group onPointerOver={() => setIndex(11)} key={11} position={[0.013, -0.335, 0.41]}>
        <Logo geometry={nodes.Vert005.geometry} material={materials['orange.001']} />
        <Logo geometry={nodes.Vert005_1.geometry} material={materials['blue.001']} />
        <Logo geometry={nodes.Vert005_2.geometry} material={materials['gray.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/skillsrotated.glb')
